# Generated by Django 4.1.6 on 2023-03-11 09:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('duration', models.PositiveIntegerField()),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.CharField(max_length=300)),
                ('image_URL', models.URLField()),
                ('upload_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('time', models.TimeField()),
                ('taken_tickets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.screens')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRepresentative',
            fields=[
                ('clubRepNumber', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('clubRepPassword', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('landline', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=11)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UWEFlix.clubrepresentative')),
            ],
        ),
    ]
